# Generated by Django 5.2.8 on 2025-11-18 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstrumental',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_equipment', models.CharField(max_length=20, verbose_name='Código')),
                ('description_equipment', models.CharField(max_length=200, verbose_name='Descripción')),
                ('supplier_equipment', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('brand_equipment', models.CharField(max_length=100, verbose_name='Marca')),
                ('model_equipment', models.CharField(max_length=50, verbose_name='Modelo')),
                ('serie_equipment', models.CharField(max_length=20, verbose_name='Serie')),
                ('date_start_use', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio Uso')),
                ('date_disabled', models.DateField(blank=True, null=True, verbose_name='Fecha de Inactivación')),
                ('time_use', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Uso (Horas)')),
                ('photo_equipment', models.FileField(blank=True, null=True, upload_to='equipment/instrumental/%Y%m%d', verbose_name='Foto del Equipo')),
                ('manual_equipment', models.FileField(blank=True, null=True, upload_to='equipment/instrumental/%Y%m%d', verbose_name='Manual de Operación')),
                ('enable_equipment', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Ubicación')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EquipmentInstrumental',
                'verbose_name_plural': 'EquipmentInstrumentals',
                'db_table': 'EquipmentInstrumental',
            },
        ),
        migrations.CreateModel(
            name='MaterialInstrumental',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_instrumental', models.CharField(max_length=20, verbose_name='Código')),
                ('description_instrumental', models.CharField(max_length=200, verbose_name='Descripción')),
                ('supplier_equipment', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('brand_instrumental', models.CharField(max_length=100, verbose_name='Marca')),
                ('date_disabled', models.DateField(blank=True, null=True, verbose_name='Fecha de Inactivación')),
                ('photo_instrumental', models.FileField(blank=True, null=True, upload_to='equipment/material/%Y%m%d', verbose_name='Foto del Equipo')),
                ('enable_instrumental', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MaterialInstrumental',
                'verbose_name_plural': 'MaterialInstrumentals',
                'db_table': 'MaterialInstrumental',
            },
        ),
    ]
