# Generated by Django 5.2.8 on 2026-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinstrumental',
            name='photo_instrumental',
            field=models.FileField(blank=True, null=True, upload_to='equipment/material/%Y%m%d', verbose_name='Foto del Material'),
        ),
    ]
