# Generated by Django 5.2.11 on 2026-03-09 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_materialinstrumental_photo_instrumental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_maintenance', models.DateField(verbose_name='Fecha')),
                ('type_maintenance', models.CharField(max_length=50, verbose_name='Tipo de Mantenimiento')),
                ('maintenance_by', models.CharField(max_length=250, verbose_name='Realizado por')),
                ('description_maintenance', models.TextField(verbose_name='Descripción del Mantenimiento')),
                ('parts_change_maintenance', models.TextField(verbose_name='Partes o Piezas Reemplazadas')),
                ('equipment_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Equipo Instrumental')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'db_table': 'Maintenance',
            },
        ),
    ]
