# Generated by Django 5.2.11 on 2026-03-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='file_maintenance',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/%Y%m%d', verbose_name='Registro Físico de Mantenimiento'),
        ),
    ]
