# Generated by Django 5.2.11 on 2026-03-27 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_maintenance_file_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='frequency_calibration',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Frecuencia de Calibración (Meses)'),
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_calibration', models.DateField(verbose_name='Fecha')),
                ('date_calibration_next', models.DateField(verbose_name='Próxima Calibración')),
                ('calibrated_by', models.CharField(max_length=250, verbose_name='Calibrado por')),
                ('parameter', models.CharField(max_length=250, verbose_name='Parametro')),
                ('observation_calibration', models.TextField(default='No aplica', verbose_name='Observaciones')),
                ('comply', models.BooleanField(verbose_name='Cumple')),
                ('certificate_calibration', models.FileField(blank=True, null=True, upload_to='calibration/%Y%m%d', verbose_name='Certificado de Calibración')),
                ('equipment_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Equipo Instrumental')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calibration',
                'verbose_name_plural': 'Calibrations',
                'db_table': 'Calibration',
            },
        ),
    ]
