# Generated by Django 5.2.11 on 2026-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipmentinstrumental_frequency_calibration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='parameter',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Parametro'),
        ),
    ]
