# Generated by Django 5.2.11 on 2026-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_calibration_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='intermediate_verification',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Verificación Intermedia (Meses)'),
        ),
    ]
