# Generated by Django 5.2.11 on 2026-03-27 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmentinstrumental_intermediate_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_verification', models.DateField(verbose_name='Fecha')),
                ('date_verification_next', models.DateField(verbose_name='Próxima Verificación')),
                ('verified_by', models.CharField(max_length=250, verbose_name='Verificado por')),
                ('parameter_verified', models.CharField(blank=True, max_length=250, null=True, verbose_name='Parametro')),
                ('reference_pattern', models.FileField(blank=True, null=True, upload_to='verification/reference_patterns/%Y%m%d', verbose_name='Patrón de Referencia')),
                ('observation_verification', models.TextField(default='No aplica', verbose_name='Observaciones')),
                ('comply', models.BooleanField(verbose_name='Cumple')),
                ('report_verification', models.FileField(blank=True, null=True, upload_to='verification/%Y%m%d', verbose_name='Reporte de Verificación')),
                ('equipment_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Equipo Instrumental')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
                'db_table': 'Verification',
            },
        ),
    ]
