# Generated by Django 5.2.11 on 2026-03-27 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='tolerance',
            field=models.FloatField(blank=True, null=True, verbose_name='Tolerancia'),
        ),
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='unit_tolerance',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Unidad de Tolerancia'),
        ),
        migrations.CreateModel(
            name='DailyVerification',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_verification_daily', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('verified_by', models.CharField(max_length=250, verbose_name='Verificado por')),
                ('parameter_verified', models.CharField(max_length=250, verbose_name='Parametro')),
                ('reference_pattern_daily', models.FloatField(verbose_name='Patrón de Referencia')),
                ('verification_result_daily', models.FloatField(verbose_name='Resultado')),
                ('error', models.FloatField(verbose_name='Error')),
                ('observation_verification', models.TextField(default='No aplica', verbose_name='Observaciones')),
                ('comply', models.BooleanField(verbose_name='Cumple')),
                ('equipment_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Equipo Instrumental')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DailyVerification',
                'verbose_name_plural': 'DailyVerifications',
                'db_table': 'DailyVerification',
            },
        ),
    ]
