# Generated by Django 5.2.11 on 2026-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_equipmentinstrumental_tolerance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='intermediate_verification',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Verificación Intermedia (Meses)'),
        ),
    ]
