# Generated by Django 5.2.11 on 2026-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_equipmentinstrumental_intermediate_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='unit_tolerance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad de Tolerancia'),
        ),
    ]
