# Generated by Django 5.2.11 on 2026-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_equipmentinstrumental_unit_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='tolerance',
            field=models.FloatField(blank=True, null=True, verbose_name='Error Máximo Permitido'),
        ),
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='unit_tolerance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad Error Máximo'),
        ),
    ]
