# Generated by Django 5.2.11 on 2026-04-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_alter_equipmentinstrumental_tolerance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='frequency_maintenance',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Frecuencia de Mantenimiento (Meses)'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='next_date_maintenance',
            field=models.DateField(default=datetime.datetime(2026, 4, 26, 22, 12, 6, 877231, tzinfo=datetime.timezone.utc), verbose_name='Fecha Próximo Mantenimiento:'),
            preserve_default=False,
        ),
    ]
