# Generated by Django 5.2.11 on 2026-04-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_equipmentinstrumental_frequency_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='Verification_pattern',
            field=models.FloatField(blank=True, null=True, verbose_name='Patrón de Verificación'),
        ),
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='unit_tolerance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
