# Generated by Django 5.2.11 on 2026-04-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_equipmentinstrumental_verification_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_next_completed',
            field=models.BooleanField(default=False, verbose_name='Próximo Mtto Completado'),
        ),
    ]
