# Generated by Django 5.2.11 on 2026-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_maintenance_maintenance_next_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='calibration_next_completed',
            field=models.BooleanField(default=False, verbose_name='Próxima Calibración completada'),
        ),
    ]
