# Generated by Django 5.2.11 on 2026-04-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_calibration_calibration_next_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentinstrumental',
            old_name='Verification_pattern',
            new_name='verification_pattern',
        ),
    ]
