# Generated by Django 5.2.11 on 2026-04-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_remove_dailyverification_responsible_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='frequency_calibration',
            field=models.FloatField(default=12, verbose_name='Frecuencia de Calibración (Meses)'),
        ),
    ]
