# Generated by Django 5.2.11 on 2026-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_alter_equipmentinstrumental_frequency_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstrumental',
            name='date_calibration_fix',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Calibración Inicial'),
        ),
    ]
