# Generated by Django 5.2.11 on 2026-05-17 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_equipmentinstrumental_date_calibration_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePattern',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_pattern', models.TextField(blank=True, null=True, verbose_name='Descripción del Patrón')),
                ('magnitude_pattern', models.FloatField(blank=True, null=True, verbose_name='Magnitud del Patrón')),
                ('unit_pattern', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad del Patrón')),
                ('equipment_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Instrumento')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ReferencePattern',
                'verbose_name_plural': 'ReferencePatterns',
                'db_table': 'ReferencePattern',
            },
        ),
    ]
