# Generated by Django 5.2.11 on 2026-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_referencepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencepattern',
            name='certificate_calibration',
            field=models.FileField(blank=True, null=True, upload_to='calibration_certificates_pattern/', verbose_name='Certificado de Calibración'),
        ),
        migrations.AddField(
            model_name='referencepattern',
            name='date_expire_calibration',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
    ]
