# Generated by Django 5.2.11 on 2026-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_referencepattern_certificate_calibration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencepattern',
            name='description_pattern',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción del Patrón'),
        ),
    ]
