# Generated by Django 5.2.11 on 2026-06-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_alter_referencepattern_description_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyverification',
            name='reference_pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.referencepattern', verbose_name='Patrón de Referencia'),
            preserve_default=False,
        ),
    ]
