# Generated by Django 5.2.11 on 2026-06-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0025_dailyverification_reference_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyverification',
            name='reference_pattern_daily',
        ),
    ]
