# Generated by Django 5.2.11 on 2026-06-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0026_remove_dailyverification_reference_pattern_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinstrumental',
            name='verification_pattern',
        ),
    ]
