# Generated by Django 6.0.7 on 2026-07-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_remove_equipmentinstrumental_verification_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinstrumental',
            name='code_instrumental',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
