# Generated by Django 6.0.7 on 2026-08-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_alter_materialinstrumental_code_instrumental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstrumental',
            name='time_use',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de Uso (Años)'),
        ),
    ]
