# Generated by Django 6.0.7 on 2026-09-26 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0029_alter_equipmentinstrumental_time_use'),
        ('sampling', '0049_samplinganalysisprocessing_absorbance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('use_date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Equipo')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('sampling_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis', verbose_name='')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EquipmentUsageLog',
                'verbose_name_plural': 'EquipmentUsageLogs',
                'db_table': 'EquipmentUsageLog',
            },
        ),
    ]
