# Generated by Django 5.2.9 on 2026-03-08 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionRegister',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('registration_date', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('registered_data', models.FloatField(verbose_name='Dato Registrado')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Acciones')),
                ('actions_registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_registered_by_conditions', to=settings.AUTH_USER_MODEL, verbose_name='Acciones Registradas por')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condition.condition', verbose_name='Área')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_by_conditions', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Condición',
                'verbose_name_plural': 'Registros de Condiciones',
                'db_table': 'ConditionRegister',
            },
        ),
    ]
