name: luka
services:
  database:
    container_name: database-luka
    image: postgres:16.8-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: luka_db
      POSTGRES_SCHEMA: public
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql
volumes:
  database_data:
