# Generated by Django 5.2.8 on 2025-12-02 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_remove_stage_process_delete_samplepoint_delete_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_product', models.CharField(max_length=30, verbose_name='Código')),
                ('description_product', models.CharField(max_length=200, verbose_name='Descripción')),
                ('enable_product', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.process', verbose_name='Planta')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=100, verbose_name='Etapa')),
                ('stage_code', models.CharField(max_length=20, verbose_name='Código')),
                ('enable_stage', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'db_table': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='SamplePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sample_point_name', models.CharField(max_length=100, verbose_name='Punto de Muestreo')),
                ('sample_point_code', models.CharField(max_length=30, verbose_name='Código')),
                ('sample_point_version', models.SmallIntegerField(default=1, verbose_name='')),
                ('sample_type', models.CharField(max_length=30, verbose_name='Tipo de Muestra (Matriz)')),
                ('enable_point', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.stage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'SamplePoint',
                'verbose_name_plural': 'SamplePoints',
                'db_table': 'SamplePoint',
            },
        ),
    ]
