# Generated by Django 5.2.8 on 2025-12-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_stage_process_delete_samplepoint_delete_stage'),
        ('product', '0002_samplepoint_date_creation_samplepoint_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.process', verbose_name='Proceso'),
        ),
    ]
