# Generated by Django 5.2.8 on 2025-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplepoint',
            name='sample_point_version',
        ),
        migrations.RemoveField(
            model_name='samplepoint',
            name='sample_type',
        ),
        migrations.AddField(
            model_name='samplepoint',
            name='sample_frequency',
            field=models.SmallIntegerField(default=1, verbose_name='Frecuencia de Muestreo'),
            preserve_default=False,
        ),
    ]
