# Generated by Django 5.2.8 on 2025-12-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_samplepoint_sample_point_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplepoint',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='process',
        ),
        migrations.AddField(
            model_name='samplepoint',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
