# Generated by Django 5.2.8 on 2025-12-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_stage_process_delete_samplepoint_delete_stage'),
        ('product', '0005_remove_samplepoint_stage_remove_product_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(default='dc2044a6-fbe6-433e-a80a-da8520d1057f', on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta'),
            preserve_default=False,
        ),
    ]
