# Generated by Django 5.2.8 on 2025-12-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepoint',
            name='sample_frequency',
            field=models.SmallIntegerField(verbose_name='Frecuencia (Horas)'),
        ),
    ]
