# Generated by Django 5.2.8 on 2025-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_samplepoint_sample_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepoint',
            name='sequence',
            field=models.SmallIntegerField(default=1, verbose_name='Secuencia'),
            preserve_default=False,
        ),
    ]
