# Generated by Django 5.2.8 on 2025-12-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_samplepoint_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepoint',
            name='sample_frequency',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Frecuencia (Horas)'),
        ),
    ]
