# Generated by Django 5.2.9 on 2026-01-08 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_analyticalmethodproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationProduct',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('test_prod', models.CharField(max_length=150, verbose_name='Ensayo')),
                ('features_prod', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('lower_limit_prod', models.FloatField(blank=True, null=True, verbose_name='Limite Inferior')),
                ('upper_limit_prod', models.FloatField(blank=True, null=True, verbose_name='Limite Superior')),
                ('unit_measure', models.CharField(max_length=10, verbose_name='Unidad de Medida')),
                ('method_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.analyticalmethodproduct', verbose_name='Método')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SpecificationProduct',
                'verbose_name_plural': 'SpecificationProducts',
                'db_table': 'SpecificationProduct',
            },
        ),
    ]
