# Generated by Django 5.2.9 on 2026-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_specificationproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationproduct',
            name='type_test',
            field=models.CharField(default=1, max_length=15, verbose_name='Tipo de Ensayo'),
            preserve_default=False,
        ),
    ]
