# Generated by Django 5.2.9 on 2026-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_specificationproduct_type_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationproduct',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
