# Generated by Django 5.2.9 on 2026-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_specificationproduct_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
    ]
