# Generated by Django 5.2.9 on 2026-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepoint',
            name='method_analytical',
            field=models.ManyToManyField(to='product.analyticalmethodproduct', verbose_name='Metodos Analíticos'),
        ),
    ]
