# Generated by Django 5.2.9 on 2026-01-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_samplepoint_method_analytical'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepoint',
            name='sample_type',
            field=models.CharField(default='Matriz', max_length=30, verbose_name='Tipo de Muestra'),
        ),
    ]
