# Generated by Django 5.2.9 on 2026-01-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_samplepoint_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepoint',
            name='periodicity',
            field=models.CharField(default='Diario', max_length=10, verbose_name='Periodicidad'),
        ),
    ]
