# Generated by Django 5.2.9 on 2026-01-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_samplepoint_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplepoint',
            name='method_analytical',
        ),
        migrations.AddField(
            model_name='samplepoint',
            name='specification',
            field=models.ManyToManyField(to='product.specificationproduct', verbose_name='Especificaciones - Metodos'),
        ),
    ]
