# Generated by Django 5.2.9 on 2026-01-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_samplepoint_method_analytical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepoint',
            name='sample_type',
            field=models.CharField(default='En Proceso', max_length=30, verbose_name='Tipo de Muestra'),
        ),
    ]
