# Generated by Django 6.0.7 on 2026-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_samplepoint_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(max_length=30, verbose_name='Código (Id)'),
        ),
    ]
