# Generated by Django 6.0.7 on 2026-07-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplepoint',
            name='sample_point_code',
            field=models.CharField(max_length=30, verbose_name='Código (Id)'),
        ),
    ]
