# Generated by Django 6.0.7 on 2026-07-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0029_alter_solutionstdbackvaluation_volume_std_back'),
        ('product', '0021_alter_samplepoint_sample_point_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationproduct',
            name='method_test_relacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethodcalculaterelation', verbose_name='Calculo'),
        ),
        migrations.AlterField(
            model_name='specificationproduct',
            name='method_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.analyticalmethodproduct', verbose_name='Método'),
        ),
    ]
