# Generated by Django 6.1.1 on 2026-10-06 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_notification_email_company_service_software'),
        ('product', '0022_specificationproduct_method_test_relacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.process', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta'),
        ),
    ]
