# Generated by Django 5.2.9 on 2026-01-13 12:19

import core.sampling.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0014_product_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingGroup',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hour_sampling', models.TimeField(verbose_name='Hora del Primer Muestreo')),
                ('hour_process', models.TimeField(verbose_name='Hora de Inicio del Proceso')),
                ('enable_sampling_group', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('sampling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.samplepoint', verbose_name='Punto de Muestreo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SamplingGroup',
                'verbose_name_plural': 'SamplingGroups',
                'db_table': 'SamplingGroup',
            },
        ),
        migrations.CreateModel(
            name='SamplingProcess',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_sampling_scheduled', models.DateTimeField(verbose_name='Programación de Muestreo')),
                ('date_sampling', models.DateTimeField(verbose_name='Fecha y Hora de Muestreo')),
                ('number_sample', models.CharField(default=core.sampling.models.code_sample_generator, max_length=15, verbose_name='N° de Muestras')),
                ('automatic_sampling', models.BooleanField(default=True, verbose_name='Muestreo Automático')),
                ('status_sampling', models.CharField(default='Programada', max_length=20, verbose_name='Estado de la Muestra')),
                ('image_sample', models.FileField(blank=True, null=True, upload_to='sampling/%Y%m%d', verbose_name='Foto de la Muestra')),
                ('group_sampling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinggroup', verbose_name='Grupo de Muestreo')),
                ('sampling_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('sampling_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SamplingProcess',
                'verbose_name_plural': 'SamplingsProcess',
                'db_table': 'SamplingProcess',
            },
        ),
    ]
