# Generated by Django 5.2.9 on 2026-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplinggroup',
            name='hour_process',
        ),
        migrations.AddField(
            model_name='samplingprocess',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de Lote'),
        ),
    ]
