# Generated by Django 5.2.9 on 2026-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_remove_samplinggroup_hour_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinggroup',
            name='number_sampling_day',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Muestras por Día'),
            preserve_default=False,
        ),
    ]
