# Generated by Django 5.2.9 on 2026-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0003_samplinggroup_number_sampling_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinggroup',
            name='hour_sampling',
            field=models.TimeField(default='07:00:00', verbose_name='Hora del Primer Muestreo'),
        ),
    ]
