# Generated by Django 5.2.9 on 2026-01-13 17:32

import core.sampling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0004_alter_samplinggroup_hour_sampling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingprocess',
            name='number_sample',
            field=models.CharField(default=core.sampling.models.code_sample_generator, max_length=25, verbose_name='N° de Muestra'),
        ),
    ]
