# Generated by Django 5.2.9 on 2026-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0005_alter_samplingprocess_number_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingprocess',
            name='number_sample',
            field=models.CharField(max_length=25, verbose_name='N° de Muestra'),
        ),
    ]
