# Generated by Django 5.2.9 on 2026-01-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0006_alter_samplingprocess_number_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingprocess',
            name='date_sampling',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Muestreo'),
        ),
    ]
