# Generated by Django 5.2.9 on 2026-01-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_samplepoint_method_analytical_and_more'),
        ('sampling', '0007_alter_samplingprocess_date_sampling'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingprocess',
            name='point_sampling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.samplepoint', verbose_name='Punto de Muestreo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplingprocess',
            name='type_sampling',
            field=models.CharField(default=1, max_length=30, verbose_name='Tipo de Muestreo'),
            preserve_default=False,
        ),
    ]
