# Generated by Django 5.2.9 on 2026-01-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_samplepoint_method_analytical_and_more'),
        ('sampling', '0008_samplingprocess_point_sampling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingprocess',
            name='group_sampling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinggroup', verbose_name='Grupo de Muestreo'),
        ),
        migrations.AlterField(
            model_name='samplingprocess',
            name='point_sampling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.samplepoint', verbose_name='Punto de Muestreo'),
        ),
    ]
