# Generated by Django 5.2.9 on 2026-01-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0009_alter_samplingprocess_group_sampling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplinggroup',
            old_name='hour_sampling',
            new_name='first_hour_sampling',
        ),
    ]
