# Generated by Django 5.2.9 on 2026-01-18 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0007_analyticalmethod_version'),
        ('sampling', '0010_rename_hour_sampling_samplinggroup_first_hour_sampling'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingAnalysis',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('average_concentration', models.FloatField(blank=True, null=True, verbose_name='Resultado')),
                ('standard_deviation', models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar')),
                ('coefficient_variation', models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('sampling_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplingprocess', verbose_name='Muestra')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SamplingAnalysis',
                'verbose_name_plural': 'SamplingsAnalysis',
                'db_table': 'SamplingAnalysis',
            },
        ),
        migrations.CreateModel(
            name='SamplingAnalysisProcessing',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity_standard', models.FloatField(verbose_name=' Cantidad de Estándar')),
                ('quantity_solution', models.FloatField(verbose_name='mL de Solución Muestra Gastados')),
                ('concentration_sln', models.FloatField(verbose_name='Concentración Sln')),
                ('analyzed_date', models.DateField(verbose_name='Fecha de Análisis')),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analizado por')),
                ('sample_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis', verbose_name='Análisis de la Muestra')),
                ('standard_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SamplingAnalysisProcessing',
                'verbose_name_plural': 'SamplingAnalysisProcessings',
                'db_table': 'SamplingAnalysisProcessing',
            },
        ),
    ]
