# Generated by Django 5.2.9 on 2026-01-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0011_samplinganalysis_samplinganalysisprocessing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplinganalysisprocessing',
            options={'verbose_name': 'SamplingAnalysisProcessing', 'verbose_name_plural': 'SamplingAnalysisProcessing'},
        ),
    ]
