# Generated by Django 5.2.9 on 2026-01-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0012_alter_samplinganalysisprocessing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysis',
            name='comply',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Concepto'),
        ),
    ]
