# Generated by Django 5.2.9 on 2026-01-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0013_samplinganalysis_comply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplinganalysisprocessing',
            old_name='concentration_sln',
            new_name='concentration_sample',
        ),
        migrations.RenameField(
            model_name='samplinganalysisprocessing',
            old_name='quantity_solution',
            new_name='quantity_sample',
        ),
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='analyzed_date',
            field=models.DateTimeField(verbose_name='Fecha de Análisis'),
        ),
    ]
