# Generated by Django 5.2.9 on 2026-01-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0014_rename_concentration_sln_samplinganalysisprocessing_concentration_sample_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysis',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='samplinganalysis',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobado'),
        ),
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='concentration_sample',
            field=models.FloatField(verbose_name='Concentración Muestra'),
        ),
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_sample',
            field=models.FloatField(verbose_name='mL Solución Muestra'),
        ),
    ]
