# Generated by Django 5.2.9 on 2026-01-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0015_samplinganalysis_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_standard',
            field=models.FloatField(verbose_name='Cant. Estándar'),
        ),
    ]
