# Generated by Django 5.2.9 on 2026-02-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0016_alter_samplinganalysisprocessing_quantity_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_standard',
            field=models.FloatField(verbose_name='mL de Sln Estándar'),
        ),
    ]
