# Generated by Django 5.2.9 on 2026-02-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0017_alter_samplinganalysisprocessing_quantity_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_sample',
            field=models.FloatField(verbose_name='Cant. de Muestra'),
        ),
    ]
