# Generated by Django 5.2.9 on 2026-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0018_alter_samplinganalysisprocessing_quantity_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_standard',
            field=models.FloatField(verbose_name='mL Estándar'),
        ),
    ]
