# Generated by Django 5.2.9 on 2026-02-16 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0019_alter_samplinganalysisprocessing_quantity_standard'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='standard_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar'),
        ),
    ]
