# Generated by Django 5.2.9 on 2026-02-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0020_alter_samplinganalysisprocessing_standard_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='relational_calculation',
            field=models.BooleanField(default=False),
        ),
    ]
