# Generated by Django 5.2.9 on 2026-02-18 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0014_alter_analyticalmethodcalculate_factor_and_more'),
        ('sampling', '0021_samplinganalysisprocessing_relational_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='analytical_method_calculate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethodcalculate'),
        ),
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='analytical_method_calculate_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethodcalculaterelation'),
        ),
    ]
