# Generated by Django 5.2.9 on 2026-03-08 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0022_samplinganalysisprocessing_analytical_method_calculate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingAnalysisProcessingRelation',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numerator', models.FloatField(verbose_name='Numerador')),
                ('denominator', models.FloatField(blank=True, null=True, verbose_name='Denominador')),
                ('calcule', models.FloatField(verbose_name='Resultado')),
                ('sampling_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SamplingAnalysisProcessingRelation',
                'verbose_name_plural': 'SamplingAnalysisProcessingRelations',
                'db_table': 'SamplingAnalysisProcessingRelation',
            },
        ),
    ]
