# Generated by Django 5.2.11 on 2026-05-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0024_samplinganalysisprocessingrelation_analytical_method_calculate_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessingrelation',
            name='sampling_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis'),
        ),
    ]
