# Generated by Django 5.2.11 on 2026-05-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0025_alter_samplinganalysisprocessingrelation_sampling_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessingrelation',
            name='sampling_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplingprocess'),
        ),
    ]
