# Generated by Django 5.2.11 on 2026-05-18 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0026_samplinganalysisprocessingrelation_sampling_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplinganalysis',
            old_name='date_approved',
            new_name='date_verified',
        ),
        migrations.RemoveField(
            model_name='samplinganalysis',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='samplinganalysis',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='samplingprocess',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='samplingprocess',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobado'),
        ),
    ]
