# Generated by Django 5.2.11 on 2026-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0027_rename_date_approved_samplinganalysis_date_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingprocess',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
