# Generated by Django 5.2.11 on 2026-05-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0028_samplingprocess_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysis',
            name='date_analysis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Análisis'),
        ),
    ]
