# Generated by Django 5.2.11 on 2026-06-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0029_samplinganalysis_date_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='weight_obtained',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Obtenido'),
        ),
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='mL Estándar'),
        ),
    ]
