# Generated by Django 5.2.11 on 2026-06-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0030_samplinganalysisprocessing_weight_obtained_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplinganalysis',
            options={'verbose_name_plural': 'SamplingsAnalysis'},
        ),
        migrations.AlterModelOptions(
            name='samplingprocess',
            options={'verbose_name_plural': 'SamplingsProcess'},
        ),
    ]
