# Generated by Django 6.0.7 on 2026-07-17 02:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0031_alter_samplinganalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinggroup',
            name='number_sampling_day',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Muestras por Día'),
        ),
        migrations.AlterField(
            model_name='samplingprocess',
            name='number_sample',
            field=models.CharField(db_index=True, max_length=45, verbose_name='N° de Muestra'),
        ),
        migrations.CreateModel(
            name='SamplingGenerationLog',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_date', models.DateField(verbose_name='Día Generado')),
                ('samples_created', models.PositiveSmallIntegerField(default=0, verbose_name='Muestras Creadas')),
                ('skipped', models.BooleanField(default=False, verbose_name='Omitido')),
                ('sampling_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinggroup', verbose_name='Grupo de Muestreo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SamplingGenerationLog',
                'verbose_name_plural': 'SamplingGenerationLogs',
                'db_table': 'SamplingGenerationLog',
                'constraints': [models.UniqueConstraint(fields=('sampling_group', 'target_date'), name='unique_group_target_date')],
            },
        ),
    ]
