# Generated by Django 6.0.7 on 2026-07-19 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0032_samplinggenerationlog_y_endurecimiento'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MillimoleReacted',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('milliliter_std_add', models.FloatField(verbose_name='Mililitros Adicionados')),
                ('milliliter_std_spend', models.FloatField(verbose_name='Mililitros Gastados')),
                ('millimole', models.FloatField(blank=True, null=True, verbose_name='Milimoles Reaccionaron')),
                ('sampling_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis')),
                ('standard_solution_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_solution_add', to='solution.solutionstd', verbose_name='Solución Estandar Adicionada')),
                ('standard_solution_spend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_solution_spend', to='solution.solutionstd', verbose_name='Solución Estandar Gastada')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MillimoleReacted',
                'verbose_name_plural': 'MillimolesReacted',
                'db_table': 'MillimoleReacted',
            },
        ),
    ]
