# Generated by Django 6.0.7 on 2026-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0033_millimolereacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='millimolereacted',
            name='quantity_sample',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad de Muestra'),
        ),
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='millimole_reacted',
            field=models.FloatField(blank=True, null=True, verbose_name='Milimoles que Reaccionan'),
        ),
    ]
