# Generated by Django 6.0.7 on 2026-07-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0034_millimolereacted_quantity_sample_and_more'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millimolereacted',
            name='millimole',
            field=models.FloatField(default=1, verbose_name='Milimoles Reaccionaron'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='millimolereacted',
            name='quantity_sample',
            field=models.FloatField(default=1, verbose_name='Cantidad de Muestra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='millimolereacted',
            name='sampling_analysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='millimolereacted',
            name='standard_solution_add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='standard_solution_add', to='solution.solutionstd', verbose_name='Solución Estandar Adicionada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='millimolereacted',
            name='standard_solution_spend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='standard_solution_spend', to='solution.solutionstd', verbose_name='Solución Estandar Gastada'),
            preserve_default=False,
        ),
    ]
