# Generated by Django 6.0.7 on 2026-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0035_alter_millimolereacted_millimole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millimolereacted',
            name='quantity_sample',
            field=models.FloatField(verbose_name='Cantidad de Muestra (g)'),
        ),
    ]
