# Generated by Django 6.0.7 on 2026-07-20 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0029_alter_solutionstdbackvaluation_volume_std_back'),
        ('sampling', '0037_alter_samplinganalysis_analytical_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysis',
            name='analytical_method_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethodcalculaterelation', verbose_name='Calculo Relacional'),
        ),
    ]
