# Generated by Django 6.0.7 on 2026-07-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0038_samplinganalysis_analytical_method_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplinganalysisprocessing',
            name='quantity_sample',
            field=models.FloatField(blank=True, null=True, verbose_name='Cant. de Muestra'),
        ),
    ]
