# Generated by Django 6.0.7 on 2026-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0039_alter_samplinganalysisprocessing_quantity_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinggroup',
            name='enable_sampling_auto',
            field=models.BooleanField(default=True, verbose_name='Automuestreo Habilitado'),
        ),
    ]
