# Generated by Django 6.0.7 on 2026-07-31 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0034_heavymetal'),
        ('sampling', '0040_samplinggroup_enable_sampling_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassiveSampleAnalysis',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('result', models.FloatField(blank=True, null=True, verbose_name='Resultado')),
                ('standard_deviation', models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar')),
                ('coefficient_variation', models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación')),
                ('comply', models.CharField(blank=True, max_length=10, null=True, verbose_name='Concepto')),
                ('date_analysis', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Análisis')),
                ('date_verified', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobado')),
                ('analized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analized_by', to=settings.AUTH_USER_MODEL, verbose_name='Analizado por')),
                ('analytical_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('sampling_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.samplingprocess', verbose_name='Muestra')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MassiveSampleAnalysis',
                'verbose_name_plural': 'MassSampleAnalysis',
                'db_table': 'MassiveSampleAnalysis',
            },
        ),
    ]
