# Generated by Django 6.0.7 on 2026-07-31 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0041_massivesampleanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massivesampleanalysis',
            name='date_verified',
        ),
    ]
