# Generated by Django 6.0.7 on 2026-07-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0042_remove_massivesampleanalysis_date_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massivesampleanalysis',
            name='date_analysis',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Análisis'),
        ),
    ]
