# Generated by Django 6.0.7 on 2026-07-31 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0034_heavymetal'),
        ('sampling', '0043_alter_massivesampleanalysis_date_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='massivesampleanalysis',
            name='heavy_metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.heavymetal', verbose_name='Metal'),
        ),
    ]
