# Generated by Django 6.0.7 on 2026-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0044_massivesampleanalysis_heavy_metal'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='blank',
            field=models.FloatField(blank=True, null=True, verbose_name='Blanco'),
        ),
    ]
