# Generated by Django 6.0.7 on 2026-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0045_samplinganalysisprocessing_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='weight_of_filter',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Filtro'),
        ),
    ]
