# Generated by Django 6.0.7 on 2026-09-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0046_samplinganalysisprocessing_weight_of_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='aliquot',
            field=models.FloatField(blank=True, null=True, verbose_name='Blanco'),
        ),
    ]
