# Generated by Django 6.0.7 on 2026-09-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0047_samplinganalysisprocessing_aliquot'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='quantity_standard_two',
            field=models.FloatField(blank=True, null=True, verbose_name='mL Estándar 2'),
        ),
    ]
