# Generated by Django 6.0.7 on 2026-09-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0048_samplinganalysisprocessing_quantity_standard_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplinganalysisprocessing',
            name='absorbance',
            field=models.FloatField(blank=True, null=True, verbose_name='Lectura del Equipo'),
        ),
    ]
