# Generated by Django 5.2.1 on 2025-06-12 03:13

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(default='Nombre Empresa', max_length=120, verbose_name='Nombre Empresa')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company', validators=[core.validators.validator_file_image], verbose_name='Logo')),
                ('company_nit', models.CharField(default='0000000000-0', max_length=20, verbose_name='NIT')),
                ('company_address', models.CharField(default='Direccion', max_length=60, verbose_name='Dirección')),
                ('company_city', models.CharField(default='Ciudad', max_length=60, verbose_name='Ciudad')),
                ('company_country', models.CharField(default='Pais', max_length=60, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('site_name', models.CharField(max_length=120, verbose_name='Planta')),
                ('site_address', models.CharField(max_length=60, verbose_name='Dirección')),
                ('site_city', models.CharField(max_length=60, verbose_name='Ciudad')),
                ('site_country', models.CharField(max_length=60, verbose_name='País')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'Site',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('process_name', models.CharField(max_length=120, verbose_name='Proceso')),
                ('enable_process', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'db_table': 'Process',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=100, verbose_name='Etapa')),
                ('stage_code', models.CharField(max_length=20, verbose_name='Codigo/Abreviación')),
                ('enable_stage', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.process', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'db_table': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='SamplePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sample_point_name', models.CharField(max_length=100, verbose_name='Punto de Muestreo')),
                ('sample_point_code', models.CharField(max_length=30, verbose_name='Codigo/Abreviación')),
                ('enable_point', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('slug', models.SlugField(unique=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.stage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'SamplePoint',
                'verbose_name_plural': 'SamplePoints',
                'db_table': 'SamplePoint',
            },
        ),
    ]
