# Generated by Django 5.2.1 on 2025-06-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_enable',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
