# Generated by Django 5.2.2 on 2025-06-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_site_site_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplepoint',
            name='slug',
        ),
    ]
