# Generated by Django 5.2.7 on 2025-10-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_samplepoint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepoint',
            name='sample_point_version',
            field=models.SmallIntegerField(default=1, verbose_name=''),
        ),
        migrations.AddField(
            model_name='samplepoint',
            name='sample_type',
            field=models.CharField(default=1, max_length=30, verbose_name='Tipo de Muestra (Matriz)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samplepoint',
            name='sample_point_code',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
