# Generated by Django 5.2.7 on 2025-10-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_samplepoint_sample_point_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sig_figs_solution',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Cifras Sign Sln'),
        ),
    ]
