# Generated by Django 5.2.7 on 2025-10-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_sig_figs_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sig_figs_solution',
        ),
        migrations.AddField(
            model_name='company',
            name='training_alert',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Alerta Capacitaciones'),
        ),
    ]
