# Generated by Django 5.2.8 on 2025-12-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_sig_figs_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='process',
        ),
        migrations.DeleteModel(
            name='SamplePoint',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
