# Generated by Django 5.2.11 on 2026-06-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_stage_process_delete_samplepoint_delete_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='autosample',
            field=models.BooleanField(default=True, verbose_name='Muestreo Automático'),
        ),
    ]
