# Generated by Django 6.0.7 on 2026-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_autosample'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notification_email',
            field=models.BooleanField(default=True, verbose_name='Notificaciones por Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_software',
            field=models.BooleanField(default=True, verbose_name='Servicio Habilitado'),
        ),
    ]
