# Generated by Django 5.2.2 on 2025-06-24 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_reagent', models.CharField(max_length=200, verbose_name='Descripción')),
                ('code_reagent', models.CharField(max_length=20, verbose_name='Código')),
                ('technical_sheet', models.FileField(upload_to='technical_sheet/%Y%m%d', verbose_name='Ficha Técnica')),
            ],
            options={
                'verbose_name': 'Reagent',
                'verbose_name_plural': 'Reagents',
                'db_table': 'Reagent',
            },
        ),
    ]
