# Generated by Django 5.2.2 on 2025-06-25 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='enable_reagent',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagent',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InventoryReagent',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('batch_number', models.CharField(max_length=50, verbose_name='N° Lote')),
                ('date_expire', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('quantity_lt', models.IntegerField(verbose_name='Cantidad (L)')),
                ('quantity_ml', models.IntegerField(verbose_name='Cantidad (mL)')),
                ('density', models.FloatField(verbose_name='Densidad (g/mL)')),
                ('reagent_liquid', models.BooleanField(default=True, verbose_name='Estado del Reactivo')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.reagent', verbose_name='Reactivo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InventoryReagent',
                'verbose_name_plural': 'InventoryReagents',
                'db_table': 'InventoryReagent',
            },
        ),
        migrations.CreateModel(
            name='TransactionReagent',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_transaction', models.DateField(verbose_name='Fecha')),
                ('use_register', models.CharField(default=True)),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('reagent_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Reactivo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransactionReagent',
                'verbose_name_plural': 'TransactionsReagent',
                'db_table': 'TransactionReagent',
            },
        ),
    ]
