# Generated by Django 5.2.2 on 2025-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0002_reagent_date_creation_reagent_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreagent',
            name='density',
        ),
        migrations.AddField(
            model_name='inventoryreagent',
            name='unit_measurement',
            field=models.CharField(default='mL', max_length=4, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='inventoryreagent',
            name='quantity_lt',
            field=models.IntegerField(verbose_name='Cantidad (L o Kg)'),
        ),
    ]
