# Generated by Django 5.2.2 on 2025-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0003_remove_inventoryreagent_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreagent',
            name='quantity_lt',
            field=models.FloatField(verbose_name='Cantidad (L o Kg)'),
        ),
        migrations.AlterField(
            model_name='inventoryreagent',
            name='quantity_ml',
            field=models.FloatField(verbose_name='Cantidad (mL)'),
        ),
    ]
