# Generated by Django 5.2.7 on 2025-10-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_samplepoint_sample_point_version_and_more'),
        ('reagent', '0004_alter_inventoryreagent_quantity_lt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reagent',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='technical_sheet/%Y%m%d', verbose_name='Ficha Técnica'),
        ),
    ]
