# Generated by Django 5.2.7 on 2025-10-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0005_reagent_site_alter_reagent_technical_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='umb',
            field=models.CharField(default=1, max_length=15, verbose_name='UMB'),
            preserve_default=False,
        ),
    ]
