# Generated by Django 5.2.7 on 2025-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0006_reagent_umb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreagent',
            name='quantity_lt',
        ),
        migrations.RemoveField(
            model_name='inventoryreagent',
            name='quantity_ml',
        ),
        migrations.RemoveField(
            model_name='inventoryreagent',
            name='reagent_liquid',
        ),
        migrations.RemoveField(
            model_name='transactionreagent',
            name='use_register',
        ),
        migrations.AddField(
            model_name='inventoryreagent',
            name='quantity_stock',
            field=models.FloatField(default=1, verbose_name='Cantidad Disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionreagent',
            name='type_transaction',
            field=models.CharField(default=1, max_length=50, verbose_name='Tipo de Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryreagent',
            name='unit_measurement',
            field=models.CharField(max_length=4, verbose_name='Unidad de Medida'),
        ),
    ]
