# Generated by Django 5.2.7 on 2025-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0007_remove_inventoryreagent_quantity_lt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreagent',
            name='detail_transaction',
            field=models.CharField(default=1, max_length=250, verbose_name='Detalle de Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryreagent',
            name='quantity_stock',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
