# Generated by Django 5.2.7 on 2025-10-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0008_transactionreagent_detail_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreagent',
            name='certificate_quality',
            field=models.FileField(default=1, upload_to='', verbose_name='Certificado de Calidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryreagent',
            name='purity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Pureza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reagent',
            name='purity_unit',
            field=models.CharField(default=1, max_length=10, verbose_name='Unidad de Pureza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reagent',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante/Marca'),
        ),
    ]
