# Generated by Django 5.2.7 on 2025-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0009_inventoryreagent_certificate_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreagent',
            name='certificate_quality',
            field=models.FileField(upload_to='certificate_quality/%Y%m%d', verbose_name='Certificado de Calidad'),
        ),
    ]
