# Generated by Django 5.2.7 on 2025-10-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0010_alter_inventoryreagent_certificate_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreagent',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='Densidad (g/mL)'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='molecular_weight',
            field=models.FloatField(default=1, verbose_name='g/mol'),
            preserve_default=False,
        ),
    ]
