# Generated by Django 5.2.7 on 2025-10-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0011_inventoryreagent_density_reagent_molecular_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='stability_solution',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días Estabilidad'),
        ),
    ]
