# Generated by Django 5.2.7 on 2025-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0012_reagent_stability_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='gram_equivalent',
            field=models.FloatField(default=1, verbose_name='Eq-gramo'),
            preserve_default=False,
        ),
    ]
