# Generated by Django 5.2.7 on 2025-10-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0013_reagent_gram_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='volumetric',
            field=models.BooleanField(default=False, verbose_name='Volumétrico'),
        ),
    ]
