# Generated by Django 5.2.7 on 2025-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0014_reagent_volumetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreagent',
            name='density',
            field=models.FloatField(default=1, verbose_name='Densidad (g/mL)'),
        ),
    ]
