# Generated by Django 5.2.7 on 2025-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0015_alter_inventoryreagent_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='molecular_weight',
            field=models.FloatField(verbose_name='Gramos/mol'),
        ),
    ]
