# Generated by Django 5.2.7 on 2025-10-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0016_alter_reagent_molecular_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='solvent',
            field=models.BooleanField(default=False, verbose_name='Solvente'),
        ),
    ]
