# Generated by Django 5.2.7 on 2025-10-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0017_reagent_solvent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='stability_solution',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días Estabilidad en Solución'),
        ),
    ]
