# Generated by Django 5.2.7 on 2025-10-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0018_alter_reagent_stability_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreagent',
            name='unit_measurement',
        ),
    ]
