# Generated by Django 5.2.7 on 2025-10-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0019_remove_inventoryreagent_unit_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='density_enable',
            field=models.BooleanField(default=False, verbose_name='Densidad'),
        ),
    ]
