# Generated by Django 5.2.7 on 2025-10-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0020_reagent_density_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreagent',
            name='certificate_quality',
            field=models.FileField(blank=True, null=True, upload_to='certificate_quality/%Y%m%d', verbose_name='Certificado de Calidad'),
        ),
    ]
