# Generated by Django 5.2.7 on 2025-10-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0021_alter_inventoryreagent_certificate_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreagent',
            name='purity',
            field=models.FloatField(verbose_name='Pureza'),
        ),
    ]
