# Generated by Django 5.2.7 on 2025-10-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0023_transactionreagent_user_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='sig_figs_solution',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Cifras Significativas'),
        ),
    ]
