# Generated by Django 5.2.7 on 2025-10-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0024_reagent_sig_figs_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='standard',
            field=models.BooleanField(default=False, verbose_name='Estándar'),
        ),
    ]
