# Generated by Django 5.2.7 on 2025-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0025_reagent_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='ready_to_use',
            field=models.BooleanField(default=False, verbose_name='STD Listo para Usar'),
        ),
    ]
