# Generated by Django 5.2.8 on 2026-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreagent',
            name='quantity',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
