# Generated by Django 6.0.7 on 2026-07-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0027_alter_transactionreagent_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='code_reagent',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='density_enable',
            field=models.BooleanField(default=False, verbose_name='Usa Densidad?'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='ready_to_use',
            field=models.BooleanField(default=False, verbose_name='STD Listo para Usar?'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='solvent',
            field=models.BooleanField(default=False, verbose_name='Uso como Solvente?'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='standard',
            field=models.BooleanField(default=False, verbose_name='Es Estándar?'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='volumetric',
            field=models.BooleanField(default=False, verbose_name='Uso Volumétrico?'),
        ),
    ]
