# Generated by Django 6.0.7 on 2026-07-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0028_alter_reagent_code_reagent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='stability_solution',
        ),
    ]
