# Generated by Django 6.0.7 on 2026-07-29 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_notification_email_company_service_software'),
        ('reagent', '0029_remove_reagent_stability_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta'),
        ),
    ]
