# Generated by Django 6.0.7 on 2026-09-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0030_alter_reagent_site'),
        ('sampling', '0049_samplinganalysisprocessing_absorbance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreagent',
            name='sampling_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis', verbose_name=''),
        ),
    ]
