# Generated by Django 5.2.7 on 2025-10-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reagent', '0011_inventoryreagent_density_reagent_molecular_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_solution', models.CharField(max_length=15, verbose_name='Código')),
                ('concentration', models.PositiveSmallIntegerField(verbose_name='Concentración')),
                ('concentration_unit', models.CharField(max_length=4, verbose_name='Unidad de Medida')),
                ('preparation_date', models.DateField(verbose_name='Fecha de Preparación')),
                ('expire_date_solution', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('quantity_solution', models.FloatField(verbose_name='Cantidad (mL)')),
                ('preparated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Preparado por')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.reagent', verbose_name='Reactivo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'db_table': 'Solution',
            },
        ),
    ]
