# Generated by Django 5.2.7 on 2025-10-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='quantity_reagent',
            field=models.FloatField(default=1, verbose_name='Cant. Reactivo (mL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='concentration',
            field=models.FloatField(verbose_name='Concentración'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='quantity_solution',
            field=models.FloatField(verbose_name='Cant. a Preparar (mL)'),
        ),
    ]
