# Generated by Django 5.2.7 on 2025-10-21 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0013_reagent_gram_equivalent'),
        ('solution', '0002_solution_quantity_reagent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='reagent',
        ),
        migrations.AddField(
            model_name='solution',
            name='inventory_reagent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Reactivo'),
            preserve_default=False,
        ),
    ]
