# Generated by Django 5.2.7 on 2025-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_remove_solution_reagent_solution_inventory_reagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='concentration_unit',
            field=models.CharField(max_length=4, verbose_name='Unidad Conc.'),
        ),
    ]
