# Generated by Django 5.2.7 on 2025-10-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0017_reagent_solvent'),
        ('solution', '0004_alter_solution_concentration_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='inventory_reagent',
        ),
        migrations.AddField(
            model_name='solution',
            name='quantity_solvent',
            field=models.FloatField(default=1, verbose_name='Solvente (mL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='solute_reagent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solute', to='reagent.inventoryreagent', verbose_name='Reactivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='solvent_reagent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solvent', to='reagent.inventoryreagent', verbose_name='Solvente'),
            preserve_default=False,
        ),
    ]
