# Generated by Django 5.2.7 on 2025-10-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0005_remove_solution_inventory_reagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='quantity_solvent',
            field=models.FloatField(blank=True, null=True, verbose_name='Solvente (mL)'),
        ),
    ]
