# Generated by Django 5.2.7 on 2025-10-21 23:49

import core.solution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0006_alter_solution_quantity_solvent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code_solution',
            field=models.CharField(default=core.solution.models.code_solution_generator, max_length=20, verbose_name='Código'),
        ),
    ]
