# Generated by Django 5.2.7 on 2025-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_alter_solution_code_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='expire_date_solution',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='preparation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación'),
        ),
    ]
