# Generated by Django 5.2.7 on 2025-10-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0008_alter_solution_expire_date_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='standardizable',
            field=models.BooleanField(default=False, verbose_name='Estandarizable'),
        ),
    ]
