# Generated by Django 5.2.7 on 2025-10-31 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0025_reagent_standard'),
        ('solution', '0009_solution_standardizable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='average_concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='Media'),
        ),
        migrations.AddField(
            model_name='solution',
            name='coefficient_variation',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación'),
        ),
        migrations.AddField(
            model_name='solution',
            name='deviation_std',
            field=models.FloatField(blank=True, null=True, verbose_name='Media'),
        ),
        migrations.CreateModel(
            name='StandarizationSolution',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity_solution', models.FloatField(verbose_name='mL de Solución')),
                ('concentration_std', models.FloatField(verbose_name='Conc. STD')),
                ('concentration_sln', models.FloatField(verbose_name='Concentración Sln')),
                ('quantity_standard', models.FloatField(verbose_name='mL Estándar')),
                ('standarization_date', models.DateField(verbose_name='Fecha de Estandarización')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='')),
                ('standard_sln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='')),
                ('standardized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StandarizationSolution',
                'verbose_name_plural': 'StandarizationSolutions',
                'db_table': 'StandarizationSolution',
            },
        ),
    ]
