# Generated by Django 5.2.7 on 2025-10-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0010_solution_average_concentration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarizationsolution',
            name='concentration_std',
        ),
    ]
