# Generated by Django 5.2.7 on 2025-10-31 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0011_remove_standarizationsolution_concentration_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarizationsolution',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solución Estándar'),
        ),
    ]
