# Generated by Django 5.2.7 on 2025-10-31 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0025_reagent_standard'),
        ('solution', '0012_alter_standarizationsolution_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarizationsolution',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='standarizationsolution',
            name='standard_sln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Solución Estándar'),
        ),
    ]
