# Generated by Django 5.2.7 on 2025-11-06 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0025_reagent_standard'),
        ('solution', '0013_alter_standarizationsolution_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='ready_to_use',
            field=models.BooleanField(default=False, verbose_name='Listo para Usar'),
        ),
        migrations.AlterField(
            model_name='standarizationsolution',
            name='standard_sln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Solución| Estándar'),
        ),
    ]
