# Generated by Django 5.2.7 on 2025-11-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0014_solution_ready_to_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='ready_to_use',
        ),
    ]
