# Generated by Django 5.2.7 on 2025-11-06 19:45

import core.solution.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0015_remove_solution_ready_to_use'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='quantity_reagent',
            field=models.FloatField(verbose_name='Cant. Reactivo'),
        ),
        migrations.AlterField(
            model_name='standarizationsolution',
            name='standard_sln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Solución Estándar'),
        ),
        migrations.CreateModel(
            name='SolutionStd',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_solution_std', models.CharField(default=core.solution.models.code_solution_generator, max_length=20, verbose_name='Código')),
                ('concentration_std', models.FloatField(verbose_name='Concentración')),
                ('concentration_unit', models.CharField(max_length=4, verbose_name='Unidad Conc.')),
                ('preparation_std_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación')),
                ('expire_std_date_solution', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('quantity_solution_std', models.FloatField(verbose_name='Cant. a Preparar (mL)')),
                ('quantity_std', models.FloatField(verbose_name='Cantidad de Estándar')),
                ('quantity_solvent', models.FloatField(blank=True, null=True, verbose_name='Solvente (mL)')),
                ('preparated_std_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Preparado por')),
                ('solute_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solute_std', to='reagent.inventoryreagent', verbose_name='Estándar')),
                ('solvent_reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent_std', to='reagent.inventoryreagent', verbose_name='Solvente')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolutionStd',
                'verbose_name_plural': 'SolutionSTDs',
                'db_table': 'SolutionStd',
            },
        ),
    ]
