# Generated by Django 5.2.7 on 2025-11-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0016_alter_solution_quantity_reagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstd',
            name='solvent_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solvent_std', to='reagent.inventoryreagent', verbose_name='Solvente'),
        ),
    ]
