# Generated by Django 5.2.7 on 2025-11-06 21:26

import core.solution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0017_alter_solutionstd_solvent_reagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstd',
            name='code_solution_std',
            field=models.CharField(default=core.solution.models.code_solution_std_generator, max_length=20, verbose_name='Código'),
        ),
    ]
