# Generated by Django 5.2.8 on 2025-11-08 03:34

import core.solution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0019_alter_solution_code_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code_solution',
            field=models.CharField(default=core.solution.models.code_solution_generator, max_length=20, verbose_name='Código'),
        ),
    ]
