# Generated by Django 5.2.8 on 2025-11-09 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0020_alter_solution_code_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standardization',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity_aliquot', models.FloatField(verbose_name='mL de Alícuota')),
                ('solution_reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='reagent.reagent', verbose_name='Solución')),
                ('solution_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_std', to='reagent.reagent', verbose_name='Solución Estándar')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standardization',
                'verbose_name_plural': 'Standardizations',
                'db_table': 'Standardization',
            },
        ),
        migrations.CreateModel(
            name='StandardizationSolution',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity_aliquot', models.FloatField(verbose_name='mL de Alícuota')),
                ('concentration_sln', models.FloatField(blank=True, null=True, verbose_name='Concentración Sln')),
                ('quantity_standard', models.FloatField(blank=True, null=True, verbose_name='mL Estándar')),
                ('standarization_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solución')),
                ('standard_sln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Solución Estándar')),
                ('standardized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StandardizationSolution',
                'verbose_name_plural': 'StandardizationSolutions',
                'db_table': 'StandardizationSolution',
            },
        ),
        migrations.DeleteModel(
            name='StandarizationSolution',
        ),
    ]
