# Generated by Django 5.2.8 on 2025-11-10 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0021_standardization_standardizationsolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standard_sln',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Solución Estándar'),
        ),
    ]
