# Generated by Django 5.2.8 on 2025-11-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0022_alter_standardizationsolution_standard_sln'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardization',
            name='molar_relation',
            field=models.FloatField(default=1, verbose_name='Relación Molar'),
        ),
    ]
