# Generated by Django 5.2.8 on 2025-11-11 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0023_standardization_molar_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSolution',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_transaction', models.DateField(verbose_name='Fecha')),
                ('type_transaction', models.CharField(max_length=50, verbose_name='Tipo de Registro')),
                ('detail_transaction', models.CharField(max_length=250, verbose_name='Detalle de Registro')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('solution_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solución')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransactionSolution',
                'verbose_name_plural': 'TransactionSolutions',
                'db_table': 'TransactionSolution',
            },
        ),
    ]
