# Generated by Django 5.2.8 on 2025-11-11 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0024_transactionsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizationsolution',
            name='quantity_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Mililitros de Estándar Gastado'),
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standard_sln',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar'),
            preserve_default=False,
        ),
    ]
