# Generated by Django 5.2.8 on 2025-11-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0025_alter_standardizationsolution_quantity_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizationsolution',
            name='quantity_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='mL Estándar'),
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standard_sln',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar'),
        ),
    ]
