# Generated by Django 5.2.8 on 2025-11-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0027_transactionsolutionstd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionsolutionstd',
            old_name='solution_inventory',
            new_name='solution_std_inventory',
        ),
    ]
