# Generated by Django 5.2.8 on 2025-11-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0028_rename_solution_inventory_transactionsolutionstd_solution_std_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstd',
            name='preparation_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
