# Generated by Django 5.2.8 on 2025-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0030_alter_solutionstd_preparated_std_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='preparation_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
