# Generated by Django 5.2.8 on 2025-12-01 00:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0032_alter_solution_preparated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardizationsolution',
            name='quantity_aliquot',
        ),
        migrations.RemoveField(
            model_name='standardizationsolution',
            name='standard_sln',
        ),
        migrations.AddField(
            model_name='standardizationsolution',
            name='quantity_solution',
            field=models.FloatField(default=1, verbose_name='mL de Solución'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardizationsolution',
            name='standard_solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='concentration_sln',
            field=models.FloatField(default=1, verbose_name='Concentración Sln'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='quantity_standard',
            field=models.FloatField(default=1, verbose_name=' Cantidad de Estándar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standardized_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standarization_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
