# Generated by Django 5.2.8 on 2025-12-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0033_remove_standardizationsolution_quantity_aliquot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardization',
            name='quantity_aliquot',
        ),
    ]
