# Generated by Django 5.2.8 on 2025-12-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0034_remove_standardization_quantity_aliquot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizationsolution',
            name='quantity_solution',
            field=models.FloatField(verbose_name='mL de Solución Gastados'),
        ),
    ]
