# Generated by Django 5.2.8 on 2025-12-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0035_alter_standardizationsolution_quantity_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='quantity_available_sln',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad Disponible (mL)'),
        ),
    ]
