# Generated by Django 5.2.8 on 2025-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0036_solution_quantity_available_sln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsolution',
            name='quantity',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='transactionsolutionstd',
            name='quantity',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
