# Generated by Django 5.2.8 on 2026-01-07 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0037_alter_transactionsolution_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionBase',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('concentration_base', models.FloatField(verbose_name='Concentración')),
                ('concentration_unit_base', models.CharField(max_length=4, verbose_name='Unidad Conc.')),
                ('enable_solution', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('solute_reagent_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solute_base', to='reagent.inventoryreagent', verbose_name='Reactivo')),
                ('solvent_reagent_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent_base', to='reagent.inventoryreagent', verbose_name='Solvente')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolutionBase',
                'verbose_name_plural': 'SolutionsBase',
                'db_table': 'SolutionBase',
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionbase', verbose_name='Solución a Preparar'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolutionStdBase',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('concentration_std_base', models.FloatField(verbose_name='Concentración')),
                ('concentration_unit_base', models.CharField(max_length=4, verbose_name='Unidad Conc.')),
                ('enable_solution_std', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('solute_std_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solute_std_base', to='reagent.inventoryreagent', verbose_name='Estándar')),
                ('solvent_reagent_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solvent_std_base', to='reagent.inventoryreagent', verbose_name='Solvente')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolutionStdBase',
                'verbose_name_plural': 'SolutionsStdBase',
                'db_table': 'SolutionStdBase',
            },
        ),
        migrations.AddField(
            model_name='solutionstd',
            name='solution_std_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solution_std', to='solution.solutionstdbase', verbose_name='Solución Estándar a Preparar'),
            preserve_default=False,
        ),
    ]
