# Generated by Django 5.2.8 on 2026-01-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0038_solutionbase_solution_solution_base_solutionstdbase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionbase',
            name='solute_reagent_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solute_base', to='reagent.reagent', verbose_name='Reactivo'),
        ),
        migrations.AlterField(
            model_name='solutionbase',
            name='solvent_reagent_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent_base', to='reagent.reagent', verbose_name='Solvente'),
        ),
    ]
