# Generated by Django 5.2.8 on 2026-01-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0027_alter_transactionreagent_quantity'),
        ('solution', '0039_alter_solutionbase_solute_reagent_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstdbase',
            name='solute_std_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solute_std_base', to='reagent.reagent', verbose_name='Estándar'),
        ),
        migrations.AlterField(
            model_name='solutionstdbase',
            name='solvent_reagent_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solvent_std_base', to='reagent.reagent', verbose_name='Solvente'),
        ),
    ]
