# Generated by Django 5.2.8 on 2026-01-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0040_alter_solutionstdbase_solute_std_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstd',
            name='solution_std_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar a Preparar'),
        ),
    ]
