# Generated by Django 5.2.8 on 2026-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0041_alter_solutionstd_solution_std_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstd',
            name='concentration_std',
            field=models.FloatField(blank=True, null=True, verbose_name='Concentración'),
        ),
        migrations.AlterField(
            model_name='solutionstd',
            name='concentration_unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Unidad Conc.'),
        ),
    ]
