# Generated by Django 6.0.7 on 2026-07-25 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='solutionstd',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratorio'),
        ),
    ]
