# Generated by Django 6.0.7 on 2026-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0043_solution_laboratory_solutionstd_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbase',
            name='stability_solution',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días Estabilidad en Solución'),
        ),
        migrations.AddField(
            model_name='solutionstdbase',
            name='stability_solution',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días Estabilidad en Solución'),
        ),
    ]
