# Generated by Django 6.0.7 on 2026-07-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('solution', '0044_solutionbase_stability_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='solutionstd',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratorio'),
        ),
    ]
