# Generated by Django 6.0.7 on 2026-07-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0045_alter_solution_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstdbase',
            name='standardizable',
            field=models.BooleanField(default=False, verbose_name='Estandarizable'),
        ),
    ]
