# Generated by Django 6.0.7 on 2026-07-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0046_solutionstdbase_standardizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbase',
            name='standardizable',
            field=models.BooleanField(default=False, verbose_name='Estandarizable'),
        ),
    ]
