# Generated by Django 6.0.7 on 2026-07-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0047_solutionbase_standardizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardization',
            name='solution_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionbase', verbose_name='Solución Base'),
        ),
        migrations.AddField(
            model_name='standardization',
            name='solution_std_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar Base'),
        ),
    ]
