# Generated by Django 6.0.7 on 2026-07-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0048_standardization_solution_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardization',
            name='solution_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_std_base', to='solution.solutionbase', verbose_name='Solución Base'),
        ),
        migrations.AlterField(
            model_name='standardization',
            name='solution_std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_std', to='solution.solutionstdbase', verbose_name='Solución Estándar'),
        ),
    ]
