# Generated by Django 6.0.7 on 2026-07-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0049_alter_standardization_solution_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardization',
            name='solution_reagent',
        ),
    ]
