# Generated by Django 6.0.7 on 2026-07-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0050_remove_standardization_solution_reagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardization',
            name='solution_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionbase', verbose_name='Solución Base'),
        ),
        migrations.AlterField(
            model_name='standardization',
            name='solution_std_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_std_base', to='solution.solutionstdbase', verbose_name='Solución Estándar Base'),
        ),
    ]
