# Generated by Django 6.0.7 on 2026-07-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0051_alter_standardization_solution_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardization',
            name='solution_std',
        ),
        migrations.AlterField(
            model_name='standardization',
            name='solution_std_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar Base'),
        ),
    ]
