# Generated by Django 6.0.7 on 2026-08-04 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0030_alter_reagent_site'),
        ('solution', '0052_remove_standardization_solution_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardization',
            name='reagent_std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reagent.reagent', verbose_name='Estándar'),
        ),
    ]
