# Generated by Django 6.0.7 on 2026-08-04 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0030_alter_reagent_site'),
        ('solution', '0053_standardization_reagent_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizationsolution',
            name='standard_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reagent.inventoryreagent', verbose_name='Estándar'),
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standard_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar'),
        ),
    ]
