# Generated by Django 6.0.7 on 2026-08-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagent', '0030_alter_reagent_site'),
        ('solution', '0054_standardizationsolution_standard_reagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardization',
            name='reagent_std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reagent.reagent', verbose_name='Estándar Primario'),
        ),
        migrations.AlterField(
            model_name='standardization',
            name='solution_std_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar Base (Primario)'),
        ),
    ]
