# Generated by Django 6.0.7 on 2026-08-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0055_alter_standardization_reagent_std_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardizationsolution',
            name='solution',
        ),
        migrations.AddField(
            model_name='standardizationsolution',
            name='solution_to_standardize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solution_to_standardize', to='solution.solutionstd', verbose_name='Solución a Estándarizar'),
        ),
        migrations.AlterField(
            model_name='standardizationsolution',
            name='standard_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_solution', to='solution.solutionstd', verbose_name='Solución Estándar'),
        ),
    ]
