# Generated by Django 6.0.7 on 2026-08-31 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0056_remove_standardizationsolution_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardization',
            name='solution_base',
        ),
        migrations.AddField(
            model_name='standardization',
            name='solution_stb_base_to_standardize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionbase', verbose_name='Solución Base a Estándarizar'),
            preserve_default=False,
        ),
    ]
