# Generated by Django 6.0.7 on 2026-08-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0057_remove_standardization_solution_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardization',
            name='solution_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionbase', verbose_name='Solución Base a Estándarizar'),
        ),
        migrations.AlterField(
            model_name='standardization',
            name='solution_stb_base_to_standardize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_stb_base_to_standardize', to='solution.solutionstdbase', verbose_name='Solución Estándar Base a Estándarizar'),
        ),
        migrations.AlterField(
            model_name='standardization',
            name='solution_std_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_std_base', to='solution.solutionstdbase', verbose_name='Solución Estándar Base (Primario)'),
        ),
    ]
