# Generated by Django 6.0.7 on 2026-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0058_standardization_solution_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstd',
            name='quantity_available_std',
            field=models.FloatField(default=0, verbose_name='Cantidad Disponible'),
            preserve_default=False,
        ),
    ]
