# Generated by Django 6.0.7 on 2026-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0059_solutionstd_quantity_available_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstd',
            name='average_concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='Media'),
        ),
        migrations.AddField(
            model_name='solutionstd',
            name='coefficient_variation',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente de Variación'),
        ),
        migrations.AddField(
            model_name='solutionstd',
            name='deviation_std',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación Estándar'),
        ),
    ]
