# Generated by Django 6.0.7 on 2026-09-26 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0049_samplinganalysisprocessing_absorbance'),
        ('solution', '0060_solutionstd_average_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsolution',
            name='sampling_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.samplinganalysis', verbose_name=''),
        ),
    ]
