# Generated by Django 6.1.1 on 2026-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0061_transactionsolution_sampling_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbase',
            name='sig_figs_solution',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Cifras Significativas [ ]'),
        ),
    ]
