# Generated by Django 6.1.1 on 2026-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0062_solutionbase_sig_figs_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstdbase',
            name='sig_figs_solution',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Cifras Significativas [ ]'),
        ),
    ]
