# Generated by Django 5.2.1 on 2025-06-03 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordhistoryuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_competence', models.CharField(max_length=200, verbose_name='Descripción')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('date_competence', models.DateField(verbose_name='Fecha Certificación')),
                ('support_competence', models.FileField(upload_to='competence/%Y%m%d', verbose_name='Soporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
                'db_table': 'Competence',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_training', models.CharField(max_length=120, verbose_name='Capacitación')),
                ('training_by', models.CharField(max_length=200, verbose_name='Realizado por')),
                ('date_training', models.DateField(verbose_name='Fecha')),
                ('support_training', models.FileField(upload_to='support_training/%Y%m%d', verbose_name='Soporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'db_table': 'Training',
            },
        ),
    ]
