# Generated by Django 5.2.1 on 2025-06-17 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_site_site_enable'),
        ('user', '0003_competence_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta'),
            preserve_default=False,
        ),
    ]
