# Generated by Django 5.2.1 on 2025-06-17 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_site_site_enable'),
        ('user', '0004_user_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta'),
        ),
    ]
