# Generated by Django 5.2.7 on 2025-10-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date_training_expire',
            field=models.DateField(default='2025-10-10', verbose_name='Fecha de Vencimiento'),
            preserve_default=False,
        ),
    ]
