# Generated by Django 5.2.7 on 2025-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_training_date_training_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_status',
            field=models.CharField(default='Vigente', max_length=30, verbose_name='Estado'),
        ),
    ]
