# Generated by Django 5.2.7 on 2025-10-12 00:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_training_training_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y%m%d', validators=[core.validators.validator_file_image_user], verbose_name='Foto'),
        ),
    ]
