# Generated by Django 5.2.7 on 2025-10-31 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date_training_alert',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 1, 3, 21, 910813, tzinfo=datetime.timezone.utc), verbose_name='Alerta Vence Capacitación'),
            preserve_default=False,
        ),
    ]
