# Generated by Django 5.2.11 on 2026-06-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_training_date_training_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_email_oss',
            field=models.BooleanField(default=False, verbose_name='Notificación Resultados OOS'),
        ),
    ]
