# Generated by Django 6.0.7 on 2026-07-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('user', '0010_user_notification_email_oss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
        migrations.AddField(
            model_name='user',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Planta'),
        ),
    ]
