# Generated by Django 6.0.7 on 2026-07-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('user', '0011_remove_user_site_user_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratorio'),
        ),
    ]
