# Generated by Django 5.2.8 on 2025-12-02 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('product', '0002_samplepoint_date_creation_samplepoint_date_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalMethod',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_analytical_method', models.CharField(max_length=250, verbose_name='Descripción')),
                ('code_analytical_method', models.CharField(max_length=20, verbose_name='Código')),
                ('enable_analytical_method', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('sample_size', models.FloatField(verbose_name='Tamaño de Muestra (g)')),
                ('type_method', models.CharField(max_length=100, verbose_name='Tipo de Método')),
                ('sig_figs_result', models.PositiveSmallIntegerField(default=2, verbose_name='Cifras Significativas')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='Laboratorio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Laboratorio')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethod',
                'verbose_name_plural': 'AnalyticalMethods',
                'db_table': 'AnalyticalMethod',
            },
        ),
    ]
