# Generated by Django 5.2.8 on 2025-12-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethod',
            name='product',
        ),
    ]
