# Generated by Django 5.2.8 on 2026-01-06 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0002_remove_analyticalmethod_product'),
        ('equipment', '0001_initial'),
        ('reagent', '0026_reagent_ready_to_use'),
        ('solution', '0037_alter_transactionsolution_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalMethodEquipment',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('equipment_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentinstrumental', verbose_name='Equipo Instrumental')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodEquipment',
                'verbose_name_plural': 'AnalyticalMethodEquipments',
                'db_table': 'AnalyticalMethodEquipment',
            },
        ),
        migrations.CreateModel(
            name='AnalyticalMethodMaterialInstrumental',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('material_instrumental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.materialinstrumental', verbose_name='Material Instrumental')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodMaterialInstrumental',
                'verbose_name_plural': 'AnalyticalMethodMaterialInstrumentals',
                'db_table': 'AnalyticalMethodMaterialInstrumental',
            },
        ),
        migrations.CreateModel(
            name='AnalyticalMethodReagent',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagent.reagent', verbose_name='Reactivo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodReagent',
                'verbose_name_plural': 'AnalyticalMethodReagents',
                'db_table': 'AnalyticalMethodReagent',
            },
        ),
        migrations.CreateModel(
            name='AnalyticalMethodSolution',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solution', verbose_name='Solución')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodSolution',
                'verbose_name_plural': 'AnalyticalMethodSolutions',
                'db_table': 'AnalyticalMethodSolution',
            },
        ),
        migrations.CreateModel(
            name='AnalyticalMethodSolutionStd',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('solution_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstd', verbose_name='Solución Estándar')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodSolutionStd',
                'verbose_name_plural': 'AnalyticalMethodSolutionStds',
                'db_table': 'AnalyticalMethodSolutionStd',
            },
        ),
    ]
