# Generated by Django 5.2.8 on 2026-01-06 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0003_analyticalmethodequipment_and_more'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalyticalMethodMaterialInstrumental',
            new_name='AnalyticalMethodMaterial',
        ),
    ]
