# Generated by Django 5.2.8 on 2026-01-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0004_rename_analyticalmethodmaterialinstrumental_analyticalmethodmaterial'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodsolution',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solutionbase', verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodsolutionstd',
            name='solution_std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar'),
        ),
    ]
