# Generated by Django 5.2.9 on 2026-01-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0006_analyticalmethodprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethod',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Versión'),
        ),
    ]
