# Generated by Django 5.2.9 on 2026-01-27 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0007_analyticalmethod_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalMethodCalculate',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('calculate_description', models.CharField(max_length=100, verbose_name='Descripción del Cálculo')),
                ('volumen_description_std', models.CharField(max_length=100, verbose_name='Descripción Estándar')),
                ('unit_measure_calculate', models.CharField(max_length=10, verbose_name='Unidad a Calcular')),
                ('numerator_factor', models.FloatField(blank=True, null=True, verbose_name='Factor Numerador')),
                ('denominator_factor', models.FloatField(blank=True, null=True, verbose_name='Factor Denominador')),
                ('general_factor', models.FloatField(blank=True, null=True, verbose_name='Factor General')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodCalculate',
                'verbose_name_plural': 'AnalyticalMethodCalculates',
                'db_table': 'AnalyticalMethodCalculate',
            },
        ),
    ]
