# Generated by Django 5.2.9 on 2026-01-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0008_analyticalmethodcalculate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='volumen_description_std',
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='volumen_std_denominator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estándar en Denominador'),
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='volumen_std_numerator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estándar en Numerador'),
        ),
    ]
