# Generated by Django 5.2.9 on 2026-01-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0009_remove_analyticalmethodcalculate_volumen_description_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='sample_gram',
            field=models.FloatField(default=1, verbose_name='Gramos de Muestra'),
            preserve_default=False,
        ),
    ]
