# Generated by Django 5.2.9 on 2026-01-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0010_analyticalmethodcalculate_sample_gram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='sample_gram',
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='sample_quantity',
            field=models.CharField(default=1, verbose_name='Muestra'),
            preserve_default=False,
        ),
    ]
