# Generated by Django 5.2.9 on 2026-01-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0011_remove_analyticalmethodcalculate_sample_gram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='sample_quantity',
            field=models.CharField(max_length=50, verbose_name='Muestra'),
        ),
    ]
