# Generated by Django 5.2.9 on 2026-01-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0012_alter_analyticalmethodcalculate_sample_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='denominator_factor',
        ),
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='general_factor',
        ),
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='numerator_factor',
        ),
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='volumen_std_denominator',
        ),
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='volumen_std_numerator',
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor'),
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='position',
            field=models.CharField(default=1, max_length=15, verbose_name='Posición en Ecuación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='volumen_std',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Volúmen Estándar'),
        ),
    ]
