# Generated by Django 5.2.9 on 2026-02-12 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0013_remove_analyticalmethodcalculate_denominator_factor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Constante'),
        ),
        migrations.CreateModel(
            name='AnalyticalMethodCalculateRelation',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('calculate_description_relation', models.CharField(max_length=100, verbose_name='Descripción del Cálculo')),
                ('unit_measure_calculate', models.CharField(max_length=10, verbose_name='Unidad a Calcular')),
                ('volumen_std', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volúmen Estándar')),
                ('factor', models.FloatField(blank=True, null=True, verbose_name='Constante')),
                ('sample_quantity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Muestra')),
                ('position', models.CharField(max_length=15, verbose_name='Posición en Ecuación')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico')),
                ('analytical_method_calculate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethodcalculate', verbose_name='Calculo Relacionado')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnalyticalMethodCalculateRelation',
                'verbose_name_plural': 'AnalyticalMethodCalculateRelations',
                'db_table': 'AnalyticalMethodCalculateRelation',
            },
        ),
    ]
