# Generated by Django 5.2.11 on 2026-04-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0014_alter_analyticalmethodcalculate_factor_and_more'),
        ('product', '0019_alter_samplepoint_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='analytical_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analítico'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculaterelation',
            name='analytical_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analitico'),
        ),
    ]
