# Generated by Django 5.2.11 on 2026-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0015_analyticalmethodcalculaterelation_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodcalculaterelation',
            name='position',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Posición en Ecuación'),
        ),
    ]
