# Generated by Django 5.2.11 on 2026-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0016_alter_analyticalmethodcalculaterelation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethod',
            name='code_analytical_method',
            field=models.CharField(max_length=20, verbose_name='Id'),
        ),
    ]
