# Generated by Django 5.2.11 on 2026-06-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0017_alter_analyticalmethod_code_analytical_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='variable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variable'),
        ),
    ]
