# Generated by Django 5.2.11 on 2026-06-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0018_analyticalmethodcalculate_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='sample_quantity',
            field=models.CharField(max_length=50, verbose_name='Variable Muestra'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='volumen_std',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variable Volúmen Estándar'),
        ),
    ]
