# Generated by Django 5.2.11 on 2026-06-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0019_alter_analyticalmethodcalculate_sample_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='calculate_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción del Cálculo'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='position',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Posición en Ecuación'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='sample_quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Variable Muestra'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='unit_measure_calculate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad a Calcular'),
        ),
    ]
