# Generated by Django 5.2.11 on 2026-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0020_alter_analyticalmethodcalculate_calculate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='multiplier_variable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variable Multiplicadora'),
        ),
    ]
