# Generated by Django 5.2.11 on 2026-06-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0021_analyticalmethodcalculate_multiplier_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticalmethodcalculate',
            name='multiplier_variable',
        ),
    ]
