# Generated by Django 5.2.11 on 2026-06-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0022_remove_analyticalmethodcalculate_multiplier_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodprocedure',
            name='step_procedure',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Paso N°'),
            preserve_default=False,
        ),
    ]
