# Generated by Django 6.0.6 on 2026-07-07 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0023_analyticalmethodprocedure_step_procedure'),
        ('solution', '0042_alter_solutionstd_concentration_std_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionStdBackValuation',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('volume_std', models.FloatField(verbose_name='Volumen Estándar')),
                ('millimoles_std', models.FloatField(verbose_name='Milimoles de Estándar')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analítico')),
                ('solution_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolutionStdBackValuation',
                'verbose_name_plural': 'SolutionStdBackValuations',
                'db_table': 'SolutionStdBackValuation',
            },
        ),
    ]
