# Generated by Django 6.0.6 on 2026-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0024_solutionstdbackvaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstdbackvaluation',
            name='volume_std',
            field=models.FloatField(verbose_name='Volumen Estándar (mL)'),
        ),
    ]
