# Generated by Django 6.0.6 on 2026-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0025_alter_solutionstdbackvaluation_volume_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstdbackvaluation',
            name='millimoles_std',
            field=models.FloatField(blank=True, null=True, verbose_name='Milimoles de Estándar'),
        ),
    ]
