# Generated by Django 6.0.6 on 2026-07-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0026_alter_solutionstdbackvaluation_millimoles_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionstdbackvaluation',
            name='millimoles_std',
        ),
    ]
