# Generated by Django 6.0.6 on 2026-07-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0027_remove_solutionstdbackvaluation_millimoles_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionstdbackvaluation',
            old_name='volume_std',
            new_name='volume_std_back',
        ),
    ]
