# Generated by Django 6.0.6 on 2026-07-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0028_rename_volume_std_solutionstdbackvaluation_volume_std_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionstdbackvaluation',
            name='volume_std_back',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen Estándar (mL)'),
        ),
    ]
