# Generated by Django 6.0.7 on 2026-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0029_alter_solutionstdbackvaluation_volume_std_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='sig_figs',
            field=models.SmallIntegerField(default=4, verbose_name='Cifras Significativas'),
        ),
    ]
