# Generated by Django 6.0.7 on 2026-07-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0031_dependentcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='consecutive_calcule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.dependentcalculation', verbose_name='Consecutivo'),
        ),
    ]
