# Generated by Django 6.0.7 on 2026-07-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0032_analyticalmethodcalculaterelation_consecutive_calcule'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='calculate_relation_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethodcalculaterelation', verbose_name='Cálculo Relacionado Add'),
        ),
    ]
