# Generated by Django 6.0.7 on 2026-07-31 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0033_analyticalmethodcalculaterelation_calculate_relation_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyMetal',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('metal_description', models.CharField(max_length=50, verbose_name='Descripción Metal')),
                ('unit_measure', models.CharField(max_length=10, verbose_name='Unidad a Calcular')),
                ('detection_limit', models.FloatField(blank=True, null=True, verbose_name='Limite de Detección')),
                ('quantification_limit', models.FloatField(blank=True, null=True, verbose_name='Limite de Cuantificación')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HeavyMetal',
                'verbose_name_plural': 'HeavyMetals',
                'db_table': 'HeavyMetal',
            },
        ),
    ]
