# Generated by Django 6.0.7 on 2026-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0034_heavymetal'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='blank_rest',
            field=models.BooleanField(default=False, verbose_name='Restar Blanco?'),
        ),
    ]
