# Generated by Django 6.0.7 on 2026-08-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0035_analyticalmethodcalculate_blank_rest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticalmethodcalculate',
            old_name='blank_rest',
            new_name='subtract_blank',
        ),
    ]
