# Generated by Django 6.0.7 on 2026-08-05 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0036_rename_blank_rest_analyticalmethodcalculate_subtract_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='operation',
            field=models.CharField(blank=True, choices=[('multiply', 'Multiplicar (×)'), ('add', 'Sumar (+)'), ('subtract', 'Restar (−)'), ('divide', 'Dividir (÷)')], max_length=10, null=True, verbose_name='Operación con el Término Anterior'),
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analytical_method.analyticalmethodcalculaterelation', verbose_name='Agrupado Dentro de'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculaterelation',
            name='calculate_relation_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_in_relations', to='analytical_method.analyticalmethodcalculaterelation', verbose_name='Cálculo Relacionado Add'),
        ),
    ]
