# Generated by Django 6.0.7 on 2026-08-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0037_analyticalmethodcalculaterelation_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='subtract_blank',
            field=models.BooleanField(default=False, verbose_name='Restar Blanco?'),
        ),
    ]
