# Generated by Django 6.0.7 on 2026-08-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0038_analyticalmethodcalculaterelation_subtract_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='variable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variable'),
        ),
    ]
