# Generated by Django 6.0.7 on 2026-08-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0041_remove_analyticalmethodcalculaterelation_sln_std_and_more'),
        ('solution', '0054_standardizationsolution_standard_reagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculaterelation',
            name='standard_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solutionstdbase', verbose_name='Solución Estándar'),
        ),
    ]
