# Generated by Django 6.0.7 on 2026-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0042_analyticalmethodcalculaterelation_standard_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='weight_of_filter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peso Filtro'),
        ),
    ]
