# Generated by Django 6.0.7 on 2026-08-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0043_analyticalmethodcalculate_weight_of_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peso Bruto'),
        ),
    ]
