# Generated by Django 6.0.7 on 2026-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0044_analyticalmethodcalculate_gross_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='aliquot',
            field=models.BooleanField(default=False, verbose_name='Alicuota'),
        ),
    ]
