# Generated by Django 6.0.7 on 2026-09-16 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0045_analyticalmethodcalculate_aliquot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GravimetryTerm',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('term_type', models.CharField(choices=[('constant', 'Valor Constante'), ('basic', 'Cálculo Básico')], max_length=10, verbose_name='Tipo de Término')),
                ('constant_value', models.FloatField(blank=True, null=True, verbose_name='Valor Constante')),
                ('operation', models.CharField(blank=True, choices=[('multiply', 'Multiplicar (×)'), ('add', 'Sumar (+)'), ('subtract', 'Restar (−)'), ('divide', 'Dividir (÷)')], max_length=10, null=True, verbose_name='Operación con el Término Anterior')),
                ('consecutive', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('analytical_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analítico')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GravimetryTerm',
                'verbose_name_plural': 'GravimetryTerms',
                'db_table': 'GravimetryTerm',
                'ordering': ['consecutive', 'date_creation'],
            },
        ),
    ]
