# Generated by Django 6.0.7 on 2026-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0046_gravimetryterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='consecutive',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden del Término'),
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='operation',
            field=models.CharField(blank=True, choices=[('multiply', 'Multiplicar (×)'), ('add', 'Sumar (+)'), ('subtract', 'Restar (−)'), ('divide', 'Dividir (÷)')], max_length=10, null=True, verbose_name='Operación con el Término Anterior'),
        ),
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='term_type',
            field=models.CharField(blank=True, choices=[('constant', 'Valor Constante'), ('basic', 'Cálculo Básico')], max_length=10, null=True, verbose_name='Tipo de Término de Ecuación'),
        ),
    ]
