# Generated by Django 6.0.7 on 2026-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0047_analyticalmethodcalculate_consecutive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodcalculate',
            name='absorbance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Absorbancia'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso Bruto'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posición en Ecuación'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='weight_of_filter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso Filtro'),
        ),
    ]
