# Generated by Django 6.0.7 on 2026-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0048_analyticalmethodcalculate_absorbance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalmethodcalculate',
            name='term_type',
            field=models.CharField(blank=True, choices=[('constant', 'Valor Constante'), ('basic', 'Cálculo Básico'), ('absorbance', 'Absorbancia')], max_length=10, null=True, verbose_name='Tipo de Término de Ecuación'),
        ),
    ]
