# Generated by Django 6.0.7 on 2026-09-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0049_alter_analyticalmethodcalculate_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodsolution',
            name='milliliter_sln',
            field=models.FloatField(blank=True, null=True, verbose_name='Mililitros'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodsolution',
            name='analytical_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analítico'),
        ),
    ]
