# Generated by Django 6.0.7 on 2026-09-26 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0050_analyticalmethodsolution_milliliter_sln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethodreagent',
            name='amount_reagent',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='analyticalmethodreagent',
            name='analytical_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytical_method.analyticalmethod', verbose_name='Método Analítico'),
        ),
    ]
