# Generated by Django 6.1.1 on 2026-10-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_method', '0051_analyticalmethodreagent_amount_reagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalmethod',
            name='unit_concentration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Concentración'),
        ),
    ]
