# Generated by Django 5.2.8 on 2025-11-18 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_remove_company_sig_figs_solution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('laboratory_name', models.CharField(max_length=120, verbose_name='Descripción del Laboratorio')),
                ('enable_laboratory', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.site', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'db_table': 'Laboratory',
            },
        ),
    ]
