# Generated by Django 6.1.1 on 2026-10-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='process',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Proceso'),
        ),
    ]
