# Generated by Django 6.1.1 on 2026-10-06 02:37

import django.db.models.deletion
from django.db import migrations, models


def forwards_process_to_fk(apps, schema_editor):
    Laboratory = apps.get_model('laboratory', 'Laboratory')
    Process = apps.get_model('company', 'Process')
    for lab in Laboratory.objects.all():
        value = lab.process
        if value is None or str(value).strip() == '':
            lab.process = None
        else:
            match = Process.objects.filter(process_name__iexact=str(value).strip()).first()
            lab.process = str(match.pk) if match else None
        lab.save(update_fields=['process'])


def backwards_process_to_char(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_notification_email_company_service_software'),
        ('laboratory', '0002_laboratory_process'),
    ]

    operations = [
        migrations.RunPython(forwards_process_to_fk, backwards_process_to_char),
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descripción del Laboratorio'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.process', verbose_name='Proceso'),
        ),
    ]
